-- Generated by nwg-displays on 2026-06-23 at 00:22:55. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "DP-1"
})
