decoration {
    active_opacity = 1
    inactive_opacity = 0.95
    rounding = 10

    blur {
        enabled = true
        xray = false
        ignore_opacity = true  # Allows opacity blurring
        new_optimizations = true
        popups = true
        input_methods = true
        size = 8
        passes = 3
        vibrancy = 0.3
    }

    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba($surfaced4)
    }
}
