# Auth
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Auto mount removable media
exec-once = udiskie

# Clipboard history
exec-once = wl-clip-persist --clipboard regular
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Cursors
exec-once = hyprctl setcursor $cursorTheme $cursorSize
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

# Resize and move windows based on matches (e.g. pip)
exec-once = caelestia resizer -d

# Start shell
exec-once = caelestia shell -d

# foreground
exec-once = sleep 1 && vesktop --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy
# exec-once = sleep 1 && vesktop
exec-once = sleep 1 && spotify-launcher
exec-once = sleep 1 && betterbird
exec-once = sleep 1 && steam -silent
exec-once = sleep 1 && heroic
exec-once = sleep 1 && kdeconnect-indicator