input {
    # keyboard
    kb_layout = us,ara,il
    repeat_rate = 35
    repeat_delay = 250

    # mouse
    sensitivity = 0
    accel_profile = flat

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}