exec = hyprctl dispatch submap global
submap = global

$mainMod = SUPER
$secondaryMod = ALT

# NOTE: Keybinds are designed to work well with the oh31 keyboard layout, you probably want to change this

# Clipboard
bind = $mainMod ctrl, R, exec, pkill fuzzel || caelestia clipboard
bind = $mainMod, equal, exec, pkill fuzzel || caelestia clipboard
bind = $mainMod ctrl shift, R, exec, pkill fuzzel || caelestia emoji -p

# Screenshots
bindel = ,Print, global, caelestia:screenshotFreeze

# Launcher
bind = $mainMod, N, global, caelestia:launcher
bindin = $mainMod, catchall, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:272, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:273, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:274, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:275, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:276, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:277, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse_up, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse_down, global, caelestia:launcherInterrupt

# Manage windows
bind = $mainMod, Return, exec, $terminal
bind = $mainMod $secondaryMod, y, exec, steam -start steam://open/library
bind = $mainMod, Q, killactive
bind = $mainMod $secondaryMod, Q, forcekillactive

# Mouse binds
bind = $mainMod, X, killactive
bindm = $mainMod, M, movewindow
bindm = $mainMod, G, resizewindow

# Layout
bind = $mainMod, period, togglesplit,
bind = $mainMod, comma, togglefloating,

# Move focus
bind = $mainMod, R, movefocus, l
bind = $mainMod, A, movefocus, r
bind = $mainMod, E, movefocus, u
bind = $mainMod, T, movefocus, d

# Switch workspaces
bind = $mainMod, J, workspace, 1
bind = $mainMod, D, workspace, 2
bind = $mainMod, Y, workspace, 3
bind = $mainMod, L, workspace, 4
bind = $mainMod, B, workspace, 5
bindr = $mainMod SHIFT, SHIFT_L, workspace, 6

# Move active window to a workspace
bind = $mainMod, C, movetoworkspace, 1
bind = $mainMod, S, movetoworkspace, 2
bind = $mainMod, I, movetoworkspace, 3
bind = $mainMod, O, movetoworkspace, 4
bind = $mainMod, F, movetoworkspace, 5
bind = $mainMod, Delete, movetoworkspace, 6

# Brightness
bindl = , XF86MonBrightnessUp, global, caelestia:brightnessUp
bindl = , XF86MonBrightnessDown, global, caelestia:brightnessDown

# Media
bindl = , XF86AudioPlay, global, caelestia:mediaToggle
bindl = , XF86AudioPause, global, caelestia:mediaToggle
bindl = , XF86AudioNext, global, caelestia:mediaNext
bindl = , XF86AudioPrev, global, caelestia:mediaPrev
bindl = , XF86AudioStop, global, caelestia:mediaStop

# Volume
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindle = , XF86AudioRaiseVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ $volumeStep%+
bindle = , XF86AudioLowerVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ $volumeStep%-
