$primary_paletteKeyColor = 777777
$secondary_paletteKeyColor = 777777
$tertiary_paletteKeyColor = 787776
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$background = 141414
$onBackground = e2e2e2
$surface = 141414
$surfaceDim = 141414
$surfaceBright = 393939
$surfaceContainerLowest = 0e0e0e
$surfaceContainerLow = 1c1c1c
$surfaceContainer = 202020
$surfaceContainerHigh = 2a2a2a
$surfaceContainerHighest = 353535
$onSurface = e2e2e2
$surfaceVariant = 474747
$onSurfaceVariant = c6c6c6
$inverseSurface = e2e2e2
$inverseOnSurface = 313131
$outline = 919191
$outlineVariant = 474747
$shadow = 000000
$scrim = 000000
$surfaceTint = c6c6c6
$primary = c6c6c6
$onPrimary = 303030
$primaryContainer = 474747
$onPrimaryContainer = e2e2e2
$inversePrimary = 5e5e5e
$secondary = c7c7c7
$onSecondary = 303030
$secondaryContainer = 474747
$onSecondaryContainer = e3e3e3
$tertiary = c8c6c4
$onTertiary = 30302f
$tertiaryContainer = 92918f
$onTertiaryContainer = 000000
$error = e4beb9
$onError = 601410
$errorContainer = 891c18
$onErrorContainer = e2e2e2
$primaryFixed = e2e2e2
$primaryFixedDim = c6c6c6
$onPrimaryFixed = 1b1b1b
$onPrimaryFixedVariant = 474747
$secondaryFixed = e3e3e3
$secondaryFixedDim = c7c7c7
$onSecondaryFixed = 1b1b1b
$onSecondaryFixedVariant = 474747
$tertiaryFixed = e5e2e0
$tertiaryFixedDim = c8c6c4
$onTertiaryFixed = 1c1b1b
$onTertiaryFixedVariant = 474746
$term0 = 343434
$term1 = 809b39
$term2 = abd89a
$term3 = cdf1ac
$term4 = 9bb09f
$term5 = bea96d
$term6 = b4d1b1
$term7 = d8d8d8
$term8 = a3a3a3
$term9 = 94b540
$term10 = b3eda0
$term11 = eafad8
$term12 = bfc2bc
$term13 = c9bf90
$term14 = c1e4bd
$term15 = ffffff
$rosewater = f1f1f1
$flamingo = e2e2e2
$pink = eddac3
$mauve = 8ecad3
$red = c0b56b
$maroon = c3bf9a
$peach = c7d2b1
$yellow = f0f2e7
$green = c5eac2
$teal = cae7ce
$sky = c0e3cb
$sapphire = a4d1b8
$blue = 90c8b2
$lavender = acd5c8
$klink = 589279
$klinkSelection = 58927a
$kvisited = 548799
$kvisitedSelection = 548799
$knegative = 858e39
$knegativeSelection = 858e39
$kneutral = 8eb847
$kneutralSelection = 8db848
$kpositive = 71ba78
$kpositiveSelection = 70ba79
$text = e2e2e2
$subtext1 = c6c6c6
$subtext0 = 919191
$overlay2 = 7e7e7e
$overlay1 = 6b6b6b
$overlay0 = 5a5a5a
$surface2 = 494949
$surface1 = 383838
$surface0 = 262626
$base = 141414
$mantle = 141414
$crust = 131313
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
