$primary_paletteKeyColor = bb5a4a
$secondary_paletteKeyColor = ad6255
$tertiary_paletteKeyColor = 997027
$neutral_paletteKeyColor = 827563
$neutral_variant_paletteKeyColor = 887456
$background = 1a1206
$onBackground = f1e0ca
$surface = 1a1206
$surfaceDim = 1a1206
$surfaceBright = 423828
$surfaceContainerLowest = 140d03
$surfaceContainerLow = 231a0d
$surfaceContainer = 271e11
$surfaceContainerHigh = 32281a
$surfaceContainerHighest = 3d3324
$onSurface = f1e0ca
$surfaceVariant = 55442a
$onSurfaceVariant = dbc3a1
$inverseSurface = f1e0ca
$inverseOnSurface = 392f20
$outline = a38d6e
$outlineVariant = 55442a
$shadow = 000000
$scrim = 000000
$surfaceTint = ffb4a7
$primary = ffb4a7
$onPrimary = 5f150b
$primaryContainer = 7d2c1f
$onPrimaryContainer = ffdad4
$inversePrimary = 9c4234
$secondary = ffb4a7
$onSecondary = 561e15
$secondaryContainer = 733429
$onSecondaryContainer = ffdad4
$tertiary = f1be6d
$onTertiary = 432c00
$tertiaryContainer = b5893e
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffdad4
$primaryFixedDim = ffb4a7
$onPrimaryFixed = 400200
$onPrimaryFixedVariant = 7d2c1f
$secondaryFixed = ffdad4
$secondaryFixedDim = ffb4a7
$onSecondaryFixed = 3a0904
$onSecondaryFixedVariant = 733429
$tertiaryFixed = ffdead
$tertiaryFixedDim = f1be6d
$onTertiaryFixed = 281900
$onTertiaryFixedVariant = 604100
$term0 = 353434
$term1 = ff563f
$term2 = ffbd9e
$term3 = ffdfd5
$term4 = b9ab66
$term5 = f18f8a
$term6 = ffba8e
$term7 = efd2c8
$term8 = b49e97
$term9 = ff8672
$term10 = ffd4c1
$term11 = fff1ed
$term12 = dcbc93
$term13 = ffa8a1
$term14 = ffd2b8
$term15 = ffffff
$rosewater = ffeeeb
$flamingo = ffd9d4
$pink = ffd2d1
$mauve = ffa9b1
$red = ff978f
$maroon = faaaa2
$peach = ffbeae
$yellow = ffeee8
$green = ffd8c1
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbac7
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = ce5c67
$kvisitedSelection = ce5c66
$knegative = eb5446
$knegativeSelection = eb5445
$kneutral = ff8a6c
$kneutralSelection = ff8a6b
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f1e0ca
$subtext1 = dbc3a1
$subtext0 = a38d6e
$overlay2 = 8f7b5e
$overlay1 = 79684f
$overlay0 = 665740
$surface2 = 544632
$surface1 = 413524
$surface0 = 2e2414
$base = 1a1206
$mantle = 1a1206
$crust = 191106
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
